# Generated by Django 4.2 on 2023-04-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
